### ISSUE TITLE
ArgumentParser --generate-completion-script=fish feedback

### ISSUE THREAD

**Issue by floam** [apple/swift-argument-parser#370]
Hi there,

I'm one of the core developers of the fish-shell, and I noticed recently that some of the binaries shipping with macOS appear to have some interesting null-terminated strings that look a whole lot like fish functions.

A couple commits enable us to easily query `shortcuts` and `kmutil` for fish completions (autoloaded after the user types the command name), https://github.com/fish-shell/fish-shell/blob/master/share/completions/shortcuts.fish and https://github.com/fish-shell/fish-shell/blob/master/share/completions/kmutil.fish. 

So, this isn't so much feedback about those two pieces of software, but just the mechanism in general this project is responsible for. 

First of all, neato! They work well. I've played around with them, and have a couple observations:

In `shortcuts view <TAB>`, for example, two things stand out: a) after entering subcommands, I am noticing the tab completions offering up useless file completions from my current directory. If there is any kind of mechanism for your generator to know whether or not files are appropriate input here, this is easily remedied, it could output `--no-files` or `--exclusive` right here and not send the user astray.

Secondly, again in e.g. `shortcuts view`, I know there are several acceptable arguments - the shortcut names output by `shortcuts list`. Would it be possible for this generator to know it could output something like `complete … -a '(shortcuts list)' … ` -- this is what I'd do by hand -- to dynamically do exactly that?

It would have to be able to produce those functions ahead of time to be evaluated at autoload time. Or if not that, another option is a way for developers to interrogate the binaries and ask them to complete strings, similar to clang. (which we use):

```fish
$ # their --autocomplete takes current partial command line. e.g.:
$ clang --autocomplete="-f"
-faapcs-bitfield-load	Follows the AAPCS standard that all volatile bit-field write generates at least one load. (ARM only).
-faapcs-bitfield-width	Follow the AAPCS standard requirement stating that volatile bit-field width is dictated by the field container type. (ARM only).
-faccess-control	
-faddrsig	Emit an address-significance table
-faggressive-function-elimination	
-falign-commons	
```

Here's a screen recording of the completions in action on fish if that is helpful to understand (the italicized grey text that appears after my cursor are not completions - those are fish's autosuggestions from my history, playing around with it earlier):

https://user-images.githubusercontent.com/291142/140467402-40033ab5-13e7-407a-adb6-bc1f7a9c7f21.mp4

Thanks!

Aaron Gyes

**Comment by natecook1000** [comment]
@floam Thanks so much for your feedback! (and as a fish-shell user, thanks for your work on that as well!) I love that there's a way for you to add auto-installation of these kinds of completions without user intervention. 👍🏻

`ArgumentParser` does provide the capability for tool developers to customize their completions, in ways that I think will address both of the issues you note for the `shortcuts view` tool. From its current behavior, it looks like that tool hasn't customized its completions, so it's getting the default behavior (which is the list of files in the current directory) for the `<shortcut-name>` argument.

When the list of possible values is known at compile-time, the completion script is able to provide those by default; otherwise, the tool developer has to specify the correct values somehow. When defining an argument, they can provide a completion parameter, of the [type defined here](https://github.com/apple/swift-argument-parser/blob/main/Sources/ArgumentParser/Parsable%20Properties/CompletionKind.swift). That parameter can specify different sources of argument values:
- a list of strings
- files in the current directory (with an optional list of extensions)
- directories in the current directory
- the results of running a separate command line program
- the results of running a Swift function with the current command line text as input

With that last option, you can define an argument in one part of a command-line tool that depends on some of the data your command line tool might provide elsewhere, which should accomplish what you're suggesting here! I'll work on improving the documentation for those completion parameters, so that we get more customization from adopters.

**Comment by floam** [comment]
Thanks for the response, that's very cool. I did at first wonder if `shortcuts` might have done just that - I noticed ArgumentParser whilst trawling through binaries and I saw telltale strings including `--custom (commandline -opc)[1..-1])'`. I was wondering how that might work. There was a short gap of time before I realized this was open source and I eventually gave up on figuring that part out through the disassembly.

Adoption of this library will be great for the ecosystem -- and I don't just mean the fish stuff, it's really facilitating nice CLI UX.
