### ISSUE TITLE
Add help level that's never visible

### ISSUE THREAD

**Issue by natecook1000** [apple/swift-argument-parser#384]
With the addition of a `--help-hidden` flag that displays an extended help screen (as in #366), command-line tool developers may want to specify a level of hidden-ness that isn't visible in that extended display. The `ArgumentHelp` type should be updated to include multiple levels of visibility instead of just using a Boolean value.

#### Existing functionality

```swift
// Hidden flag
@Flag(help: .hidden)
var experimentalExtraSpicy = false

// Hidden flag, but with abstract provided
@Flag(help: ArgumentHelp("Experimental extra sauce setting", shouldDisplay: false))
var experimentalExtraSauce = false
```

#### Proposed

A visibility API:

```swift
enum Visibility {
    /// Show help for this argument whenever appropriate
    case default

    /// Only show help for this argument in the extended help screen
    case hidden

    /// Never show help for this argument
    case private
}
```

...and its use at the declaration site:

```swift
// Hidden flag
@Flag(help: .hidden)
var experimentalExtraSpicy = false

// Hidden flag, but with abstract provided
@Flag(help: ArgumentHelp("Experimental extra sauce setting", visibility: .hidden))
var experimentalExtraSauce = false

// Private flag
@Flag(help: .private)
var deprecatedFlag = false
```

**Comment by McNight** [comment]
Hello @natecook1000 and others,
I want to get involved in some Swift projects I particularly like and I saw that this issue was a good opportunity 😃
[I already started to implement it](https://github.com/McNight/swift-argument-parser/tree/mcnight/argumenthelp_visibility_levels), following your proposed API. However, I have some questions:
- do you think it's suitable right now for a draft pull request ?
- some tests rely on the old API where some arguments are expected to be hidden so what should we do ? modify the expectations or modify the `ParsableArguments` entities (using the new API) ? Also new tests obviously have to be added!
- what about documentation ?
Thanks!

**Comment by natecook1000** [comment]
@McNight — thanks for your interest in contributing! Feel free to open a draft PR whenever you're ready for feedback.

Since #366 hasn't landed yet, the work you're doing won't have any visible effects. There shouldn't need to be any changes to existing tests, just new unit tests that exercise the new API. Note that all the API in _existing_ tests needs to stay for source compatibility, so if some of the tests are no longer compiling, that's a cue that something got lost. You can add deprecated versions of old API that call through to your new API to resolve those.

For documentation, please follow what's there for API documentation, or feel free to expand on it! I'll take a look at where this impacts the accompanying articles. 👍🏻

**Comment by McNight** [comment]
Happy to help @natecook1000 😃
