### ISSUE TITLE
Init of AsyncParsableCommand is called multiple times

### ISSUE THREAD

**Issue by doozMen** [apple/swift-argument-parser#523]
I have a simple command, see below, that runs a custom build command. I have to do some initial setup that can only happen once. I noticed init gets called many times when I use @main. 

```swift
import ArgumentParser

@main
struct Build: AsyncParsableCommand {
 
  static var configuration: CommandConfiguration = .init(
    subcommands: [BuildSwift.self, Clean.self])
  
  init() { print("Init called")}
}

```

**ArgumentParser version:** `1.2.0`
**Swift version:** 
swift-driver version: 1.62.15 Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0
Darwin MacBook-Pro.lan 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64

### Checklist
- [ ] If possible, I've reproduced the issue using the `main` branch of this package
- [ ] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce
1. swift package init --type executable
2. depend on swift-argument-parser
3. add build command like above 
4. run the app

### Expected behavior

Init should only be called once

### Actual behavior

multiple calls to init

### Workaround

I overwrite the static main and copy paste the default implementation of AsyncParsableCommand. This one is only called once. But not ideal

**Comment by rauhul** [comment]
Just a drive by comment... I'm surprised (and sorta don't believe[1]) you see a difference by copying the default implementation of `main`. This is because we use the following pattern in argument parser quite a bit: `Mirror(reflecting: type.init())`. For example you'll see this in `ArgumentSet.init(_:, visibility:, parent:)` and `ParsableArgumentsValidator.validate(_:, parent:)`. Each time a mirror is constructed you'll see a call to your parseable command type's `init`. 

This doesn't seem trivially solvable but @natecook1000 likely has additional thoughts (probably after the thanksgiving break).

[1]: Could you attach a full sample project and the exact command line arguments passed?

**Comment by natecook1000** [comment]
Since the default initializer (`init()`) for the command provides the configuration data for all of the command's properties, it shouldn't have side-effects beyond creating that default instance. As a performance improvement, we could probably cache these instances the first time they're created, but we still wouldn't want to guarantee a single initialization call. (Indeed, at some point we might not need to call that initializer at all).

If you need one-time-only setup, I would place it in a lazily executed closure (e.g. assigning a global variable) or override `main` and call it from there before kicking off command parsing/execution.
