### ISSUE TITLE
helpRequested(visibility: ArgumentParser.ArgumentVisibility(base: ArgumentParser.ArgumentVisibility.Representation.default))

### ISSUE THREAD

**Issue by davidnorris78** [apple/swift-argument-parser#545]
Replace this paragraph with a short description of the incorrect incorrect behavior. If this is a regression, please note the last version that the behavior was correct in addition to your current version.

**ArgumentParser version:** `0.1.0` or the `main` branch, for example.
**Swift version:** Paste the output of `swift --version` here.

### Checklist
- [x] If possible, I've reproduced the issue using the `main` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce
I'm building a commandline tool that runs as root and I'm simply attempting to get the '--help' to present when there are no arguments passed into the command line.

I'm running Macbook Pro M1, Xcode Version 14.2 (14C18) as sudo.

Here is my logic in main.swift
```
let passedArgs = Array(CommandLine.arguments.dropFirst())
if passedArgs.count == 0 {
    do {
        try _ = argParser.parse(["--help"])
        exit(1)
    } catch {
        print(error)
        print(error.localizedDescription)
        exit(1)
    }
}
```

### Expected behavior
Expecting it to print out the Help/Usage summary of each of the commands.

### Actual behavior
Console in Xcode just returns:

```
helpRequested(visibility: ArgumentParser.ArgumentVisibility(base: ArgumentParser.ArgumentVisibility.Representation.default))
The operation couldn’t be completed. (ArgumentParser.ParserError error 0.)
```

**Comment by natecook1000** [comment]
The `parse(_:)` method that you're calling either returns a parsed instance of your `argParser` type or throws an error. Since you're passing the `--help` flag, it can't produce a parsed instance, so it throws an "error" that indicates that a help request has been made.

Once you catch `error`, you have a couple options:
- You can call `argParser.exit(with: error)` to print the correct message for the error and exit with an appropriate error code — the help screen and `0`, in this case.
- You can call `argParser.fullMessage(for: error)` and `argParser.exitCode(for: error)` to get the message and error code separately, in case you have additional logic you need.

Alternatively, you can replace all of the code you have there with just `argParser.main()` or by adding `@main` to your `argParser` declaration — printing the help screen is the default behavior when no inputs are passed.
